name: Test and Build

on:
  push:
    branches:
      - dev
      - master
      - OSS-50-Create-CI-CD-file-for-Githib-Actions
  pull_request:
    branches:
      - dev
      - master
      - OSS-50-Create-CI-CD-file-for-Githib-Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package -DskipTests --file pom.xml